# Generated by Django 4.2.16 on 2024-10-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subunit', models.CharField(blank=True, max_length=30, null=True, verbose_name='Подразделение')),
                ('odpu_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='№ ОДПУ')),
                ('energy_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Вид энерг-а ГВС')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес объекта')),
                ('object_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип объекта')),
                ('current_consumption', models.CharField(blank=True, max_length=30, null=True, verbose_name='Текущее потребление, Гкал')),
                ('period', models.DateField(help_text='2022-08-01', verbose_name='Период (мес, год)')),
                ('floors', models.CharField(blank=True, max_length=50, null=True, verbose_name='Этажность объекта')),
                ('construction_date', models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата постройки')),
                ('area', models.CharField(blank=True, max_length=30, null=True, verbose_name='Общая площадь объекта')),
                ('specific_data', models.FloatField(blank=True, null=True, verbose_name='Удельное потребление, Гкал/1кв.м')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Модель по анализу потреблению многоэтажками',
                'verbose_name_plural': 'Модель по анализу потреблению многоэтажками',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='DoubleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subunit', models.CharField(blank=True, max_length=30, null=True, verbose_name='Подразделение')),
                ('odpu_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='№ ОДПУ')),
                ('energy_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Вид энерг-а ГВС')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес объекта')),
                ('object_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип объекта')),
                ('current_date', models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата текущего показания')),
                ('current_consumption', models.CharField(blank=True, max_length=30, null=True, verbose_name='Текущее потребление, Гкал')),
                ('period', models.DateField(help_text='2022-08-01', verbose_name='Период (мес, год)')),
            ],
            options={
                'verbose_name': 'Равные данные по потреблению в несколких периодах',
                'verbose_name_plural': 'Равные данные по потреблению в несколких периодах',
                'ordering': ['-current_consumption'],
            },
        ),
    ]
