# Generated by Django 4.2.16 on 2024-10-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDataReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес объекта')),
                ('object_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип объекта')),
                ('floors', models.CharField(blank=True, max_length=50, null=True, verbose_name='Этажность объекта')),
                ('construction_date', models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата постройки')),
                ('area', models.CharField(blank=True, max_length=30, null=True, verbose_name='Общая площадь объекта')),
                ('subunit', models.CharField(blank=True, max_length=30, null=True, verbose_name='Подразделение')),
                ('odpu_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='№ ОДПУ')),
                ('energy_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Вид энерг-а ГВС')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Данные по объекту + из отчета потребления',
                'verbose_name_plural': 'Данные по объектам + из отчетов потребления',
                'ordering': ['address'],
            },
        ),
    ]
