# Generated by Django 4.2.16 on 2024-10-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0002_objectdatareport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='construction_date',
            field=models.CharField(blank=True, help_text='2022-08-01', max_length=20, null=True, verbose_name='Дата постройки'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='period',
            field=models.CharField(help_text='2022-08-01', max_length=20, verbose_name='Период (мес, год)'),
        ),
    ]
