# Generated by Django 4.2.16 on 2024-10-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0003_alter_apartment_construction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='period',
            field=models.DateField(help_text='2022-08-01', verbose_name='Период (мес, год)'),
        ),
    ]
