# Generated by Django 4.2.16 on 2024-10-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0004_alter_apartment_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='construction_date',
            field=models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата постройки'),
        ),
    ]
