# Generated by Django 4.2.16 on 2024-10-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0005_alter_apartment_construction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['address'], 'verbose_name': 'Модель по анализу потребления многоэтажками', 'verbose_name_plural': 'Модель по анализу потребления многоэтажками'},
        ),
        migrations.AlterField(
            model_name='doubledata',
            name='current_date',
            field=models.CharField(blank=True, help_text='2022-08-01', max_length=20, null=True, verbose_name='Дата текущего показания'),
        ),
        migrations.AlterField(
            model_name='doubledata',
            name='period',
            field=models.CharField(help_text='2022-08-01', max_length=20, verbose_name='Период (мес, год)'),
        ),
    ]
