# Generated by Django 4.2.16 on 2024-10-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0006_alter_apartment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='construction_date',
            field=models.CharField(blank=True, help_text='2022-08-01', max_length=20, null=True, verbose_name='Дата постройки'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='period',
            field=models.CharField(help_text='2022-08-01', max_length=20, verbose_name='Период (мес, год)'),
        ),
        migrations.AlterField(
            model_name='doubledata',
            name='current_date',
            field=models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата текущего показания'),
        ),
        migrations.AlterField(
            model_name='doubledata',
            name='period',
            field=models.DateField(help_text='2022-08-01', verbose_name='Период (мес, год)'),
        ),
    ]
