# Generated by Django 4.2.16 on 2024-10-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0007_alter_apartment_construction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectdatareport',
            name='construction_date',
            field=models.CharField(blank=True, help_text='2022-08-01', max_length=20, null=True, verbose_name='Дата постройки'),
        ),
    ]
