# Generated by Django 4.2.16 on 2024-10-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0008_alter_objectdatareport_construction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectdatareport',
            options={'ordering': ['address'], 'verbose_name': 'Данные по объекту с учетом отчета потребления', 'verbose_name_plural': 'Данные по объектам с учетом отчетов потребления'},
        ),
        migrations.RemoveField(
            model_name='objectdatareport',
            name='energy_type',
        ),
        migrations.RemoveField(
            model_name='objectdatareport',
            name='odpu_number',
        ),
        migrations.RemoveField(
            model_name='objectdatareport',
            name='subunit',
        ),
    ]
