# Generated by Django 4.2.16 on 2024-10-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0009_alter_objectdatareport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='object_group',
            field=models.IntegerField(blank=True, null=True, verbose_name='Группа объекта'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая площадь объекта'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этажность объекта'),
        ),
    ]
