# Generated by Django 4.2.16 on 2024-10-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0010_apartment_object_group_alter_apartment_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='floors',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Этажность объекта'),
        ),
    ]
