# Generated by Django 4.2.16 on 2024-10-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0012_apartment_median_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['current_consumption'], 'verbose_name': 'Модель по анализу потребления многоэтажками', 'verbose_name_plural': 'Модель по анализу потребления многоэтажками'},
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='median_value',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='median_value_deviation',
        ),
        migrations.AddField(
            model_name='apartment',
            name='index_abnormal',
            field=models.FloatField(blank=True, null=True, verbose_name='Индекс потребления от медианы: >25%(-1), <25%(1), другое (0)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='median_value_s_deviation',
            field=models.FloatField(blank=True, null=True, verbose_name='Коэффициент отклонения от медианы'),
        ),
    ]
