# Generated by Django 4.2.16 on 2024-11-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0013_alter_apartment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['current_consumption'], 'verbose_name': 'Apartment - Модель анализа потребления многоэтажками', 'verbose_name_plural': 'Apartment - Модель анализа потребления многоэтажками'},
        ),
    ]
