# Generated by Django 4.2.16 on 2024-11-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_anomaly_detection', '0003_forecastdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdata',
            name='forecast_deviation',
            field=models.FloatField(blank=True, null=True, verbose_name='Коэффициент (прогноз/факт) удельного потребления'),
        ),
    ]
