# Generated by Django 4.2.16 on 2024-10-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subunit', models.CharField(max_length=30, verbose_name='Подразделение')),
                ('odpu_number', models.CharField(max_length=50, verbose_name='№ ОДПУ')),
                ('energy_type', models.CharField(max_length=30, verbose_name='Вид энерг-а ГВС')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес объекта')),
                ('object_type', models.CharField(max_length=30, verbose_name='Тип объекта')),
                ('current_date', models.DateField(help_text='2022-08-01', verbose_name='Дата текущего показания')),
                ('current_consumption', models.CharField(max_length=30, verbose_name='Текущее потребление, Гкал')),
                ('period', models.DateField(help_text='2022-08-01', verbose_name='Период (год, мес)')),
                ('generated_by', models.CharField(max_length=50, verbose_name='Сформировал')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Данные по потреблению тепловой энергии',
                'verbose_name_plural': 'Данные по потреблению тепловой энергии',
                'ordering': ['-period'],
            },
        ),
    ]
