# Generated by Django 4.2.16 on 2024-10-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_energydata_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyDataTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subunit', models.CharField(blank=True, max_length=30, null=True, verbose_name='Подразделение')),
                ('odpu_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='№ ОДПУ')),
                ('energy_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Вид энерг-а ГВС')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес объекта')),
                ('object_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип объекта')),
                ('current_date', models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата текущего показания')),
                ('current_consumption', models.CharField(blank=True, max_length=30, null=True, verbose_name='Текущее потребление, Гкал')),
                ('period', models.DateField(help_text='2022-08-01', verbose_name='Период (мес, год)')),
                ('generated_by', models.CharField(max_length=50, verbose_name='Сформировал')),
                ('created_date', models.DateField(null=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Исторические данные по потреблению тепловой энергии',
                'verbose_name_plural': 'Исторические данные по потреблению тепловой энергии',
                'ordering': ['-period'],
            },
        ),
        migrations.AlterModelOptions(
            name='energydata',
            options={'ordering': ['-period'], 'verbose_name': 'Данные по потреблению тепловой энергии за последний месяц', 'verbose_name_plural': 'Данные по потреблению тепловой энергии за последний месяц'},
        ),
        migrations.AlterField(
            model_name='energydata',
            name='created_date',
            field=models.DateField(null=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='period',
            field=models.DateField(help_text='2022-08-01', verbose_name='Период (мес, год)'),
        ),
    ]
