# Generated by Django 4.2.16 on 2024-10-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_energydatatotal_alter_energydata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес объекта')),
                ('object_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип объекта')),
                ('floors_count', models.CharField(blank=True, max_length=50, null=True, verbose_name='Этажность объекта')),
                ('construction_date', models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата постройки')),
                ('area', models.CharField(blank=True, max_length=30, null=True, verbose_name='Общая площадь объекта')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Данные по объекту ',
                'verbose_name_plural': 'Данные по объектам',
                'ordering': ['address'],
            },
        ),
    ]
