# Generated by Django 4.2.16 on 2024-10-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_anomalenergydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDataLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес объекта')),
                ('object_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип объекта')),
                ('floors', models.CharField(blank=True, max_length=50, null=True, verbose_name='Этажность объекта')),
                ('construction_date', models.CharField(blank=True, help_text='2022-08-01', max_length=15, null=True, verbose_name='Дата постройки')),
                ('area', models.CharField(blank=True, max_length=30, null=True, verbose_name='Площадь объекта')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Загрузка объекта ',
                'verbose_name_plural': 'Загрузки по объектам',
                'ordering': ['address'],
            },
        ),
        migrations.RenameField(
            model_name='objectdata',
            old_name='floors_count',
            new_name='floors',
        ),
        migrations.AddField(
            model_name='objectdata',
            name='object_area',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Площадь объекта'),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='construction_date',
            field=models.CharField(blank=True, help_text='2022-08-01', max_length=15, null=True, verbose_name='Дата постройки'),
        ),
    ]
